name: kg-algo-env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - libcxx=14.0.6
  - libffi=3.3
  - ncurses=6.4
  - openssl=1.1.1w
  - python=3.10.0
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - annotated-types==0.7.0
    - anyio==4.7.0
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - distro==1.9.0
    - exceptiongroup==1.2.2
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.27.0
    - idna==3.10
    - jiter==0.8.2
    - numpy==1.26.4
    - openai==1.41.0
    - packaging==24.2
    - pip==24.2
    - pipdeptree==2.24.0
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - python-dotenv==1.0.1
    - regex==2024.11.6
    - requests==2.32.3
    - setuptools==75.1.0
    - sniffio==1.3.1
    - tiktoken==0.8.0
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - urllib3==2.3.0
    - wheel==0.44.0
prefix: /Users/ken/opt/miniconda3/envs/kg-algo-env
